name: Deploy to ECS from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull hemanth42079/medusa-store:latest
          echo "Pulled image: hemanth42079/medusa-store:latest"

      # Register a new ECS task definition with the latest image
      - name: Update ECS task definition
        id: update-task-def
        run: |
          # Fetch the current task definition
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition medusa-task \
            --region us-east-1)

          # Modify the task definition to use the new image
          NEW_TASK_DEF=$(echo "$TASK_DEF" | jq \
            '.taskDefinition |
            .containerDefinitions[0].image = "hemanth42079/medusa-store:latest" |
            del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          # Register the new task definition
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --region us-east-1 \
            --cli-input-json "$NEW_TASK_DEF" \
            | jq -r '.taskDefinition.taskDefinitionArn')

          echo "New task definition ARN: $NEW_TASK_DEF_ARN"
          echo "task_definition_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_OUTPUT

      # Update the ECS service with the new task definition and force deployment
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --task-definition ${{ steps.update-task-def.outputs.task_definition_arn }} \
            --force-new-deployment \
            --region us-east-1
          echo "Updated ECS service with new task definition"

      # Wait for ECS service to stabilize
      - name: Wait for ECS service stability
        run: |
          aws ecs wait services-stable \
            --cluster medusa-cluster \
            --services medusa-service \
            --region us-east-1
          echo "ECS service has stabilized"
