name: Deploy Medusa Store to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ronikgandhi/medusa-store:latest .

      # ✅ Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ronikgandhi/medusa-store:latest

      # ✅ Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ✅ Step 7: Write ECS task definition JSON
      - name: Write ECS task definition file
        run: |
          cat > ecs-task-definition.json <<EOF
          {
            "family": "medusa-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "medusa-container",
                "image": "ronikgandhi/medusa-store:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 3000,
                    "hostPort": 3000
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF

      # ✅ NEW Step: Fill in the new image
      - name: Fill in new image
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          container-name: medusa-container
          image: ronikgandhi/medusa-store:latest

      # ✅ NEW Step: Deploy updated task definition to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          cluster: medusa-cluster
          service: medusa-service
          wait-for-service-stability: true
