name: Deploy Medusa Store to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ronikgandhi/medusa-store:latest .

      # 5. Push to Docker Hub
      - name: Push Docker image
        run: |
          docker push ronikgandhi/medusa-store:latest

      # 6. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 7. Write task definition
      - name: Write ECS task definition file
        run: |
          cat > ecs-task-definition.json <<EOF
          {
            "family": "medusa-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "medusa-container",
                "image": "ronikgandhi/medusa-store:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 3000,
                    "hostPort": 3000
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF

      # 8. Register task definition + output ARN
      - name: Register ECS task definition
        id: register-task-def
        run: |
          NEW_TASK_DEF=$(aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json \
            --region us-east-1)

          NEW_TASK_DEF_ARN=$(echo "$NEW_TASK_DEF" | jq -r '.taskDefinition.taskDefinitionArn')

          echo "task_definition_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_OUTPUT

      # 9. Update ECS service
      - name: Update ECS service
        run: |
          echo "Updating ECS service to use task definition: ${{ steps.register-task-def.outputs.task_definition_arn }}"
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --task-definition ${{ steps.register-task-def.outputs.task_definition_arn }} \
            --force-new-deployment \
            --region us-east-1

      # 10. Wait for service to stabilize
      - name: Wait for ECS service to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster medusa-cluster \
            --services medusa-service \
            --region us-east-1

          echo "✅ ECS service is now stable"
